name: Workspace Action
description: Workspace deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  name:
    description: "Workspace Name"
    required: true
    default: ""
  email:
    description: "Email"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Workspace deployment
      env:
        API: ${{ github.action_path }}/../../.payload_templates/api
        email: ${{ inputs.email }}
      run: |
        cd ${{ inputs.folder }}
        babylon api workspace create ${{ inputs.name }} -i $API/workspace.yaml -e $email -r admin -s
      shell: bash
