name: Workspace Action
description: Workspace deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  name:
    description: 'Workspace name object'
    required: true
    default: ''
  email:
    description: 'Workspace email security'
    required: true
    default: ''
  role:
    description: 'Workspace role security'
    required: true
    default: 'Admin'
  context_id:
    description: 'Workspace Context Name'
    required: true
    default: 'asset'
  platform_id:
    description: 'Workspace Platform Name'
    required: true
    default: 'dev'

runs:
  using: "composite"
  steps:
    - name: Workspace deployment
      if: ${{ inputs.name != '' && inputs.email != '' }}
      run: |
        cd ${{ inputs.folder }}
        babylon config set -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} powerbi scenario_view None 
        babylon api workspaces payload create -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon api workspaces create "${{ inputs.name }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon api workspaces security add -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --email ${{ inputs.email }} --role ${{ inputs.role }}
        babylon api workspaces send-key -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
      shell: bash
