name: Configuration Action 
description: Setup babylon configuration Action
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  deploy:
    description: Deploy json object
    required: true
    default: ''
  platform:
    description: Platform json object
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: setup babylon configuration
      run: |
        cd ${{ inputs.folder }}
        python ${{ github.action_path }}/set_babylon_config.py '${{ toJSON(inputs) }}'
      shell: bash
