name: PowerBI Action
description: PowerBI deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  workspace_name: 
    description: "report powerbi name"
    required: true
    default: ""
  database_name:
    description: "adx cluster database"
    required: true
    default: ""    
  cluster_name:
    description: "adx cluster url"
    required: true
    default: ""
  user_name:
    description: "add Access to user in powerBI"
    required: true 
    default: ""
runs:
  using: "composite"
  steps:
    - name: PowerBI deployment
      env:
        POWERBI: ${{ github.action_path }}/../../../powerbi/*.pbix
        database_name: ${{ inputs.database_name }}
        cluster_name: ${{ inputs.cluster_name }}
      run: |
        cd ${{ inputs.folder }}
        babylon powerbi workspace create "${{ inputs.workspace_name }}" -s
        pwid=$(babylon config get-variable deploy 'powerbi_workspace_id')
        babylon powerbi report upload -w "$pwid" "$POWERBI"
        dataset=$(babylon powerbi report get-all -w "$pwid" --filter [0].datasetId)
        id=$(echo "$dataset" | tr -d "'")
        babylon config set-variable deploy 'dataset_id' $id
        babylon powerbi workspace user add -w "$pwid" "${{ inputs.user_name }}"  User Member
        dID=$(babylon config get-variable deploy 'dataset_id')
        babylon powerbi dataset update-credentials -w "$pwid" "$dID"
      shell: bash