name: PowerBI Action
description: PowerBI deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  name:
    description: 'Workspace Powerbi Name'
    required: true
    default: ''
  type_dashboard_view:
    description: 'dashboard_view'
    required: true
    default: ''
  type_scenario_view:
    description: 'scenario_view'
    required: true
    default: ''
  context_id:
    description: 'Context Name'
    required: true
    default: 'asset'
  platform_id:
    description: 'Platform Name'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: PowerBI deployment
      env:
        POWERBI: ${{ github.action_path }}/../../../powerbi/dashboard
      run: |
        cd ${{ inputs.folder }}
        babylon powerbi workspace deploy "${{ inputs.name }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --type "${{ inputs.type_dashboard_view }}" --folder $POWERBI/ --override
      # babylon powerbi workspace deploy "${{ inputs.name }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --type "${{ inputs.type_scenario_view }}" --folder $POWERBI/ --override  
      shell: bash

