name: PowerBI Action
description: PowerBI deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  workspace_name_dashboard:
    description: 'Workspace Powerbi Name dashboard'
    required: true
    default: ''
  workspace_name_scenario:
    description: 'Workspace Powerbi Name scenario'
    required: true
    default: ''
  type_dashboard_view:
    description: 'dashboard_view'
    required: true
    default: ''
  type_scenario_view:
    description: 'scenario_view'
    required: true
    default: ''
  context_id:
    description: 'Context Name'
    required: true
    default: 'asset'
  platform_id:
    description: 'Platform Name'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: PowerBI deployment
      env:
        powerbi_dashboard_view: ${{ github.action_path }}/../../../powerbi/dashboard
        powerbi_scenario_view: ${{ github.action_path }}/../../../powerbi/scenario
      run: |
        cd ${{ inputs.folder }}
        babylon powerbi workspace deploy "${{ inputs.workspace_name_dashboard }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --type ${{ inputs.type_dashboard_view }} --folder $powerbi_dashboard_view/ --override
        babylon powerbi workspace deploy "${{ inputs.workspace_name_scenario }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --type "${{ inputs.type_scenario_view }}" --folder $powerbi_scenario_view/ --override  
      shell: bash

