name: PowerBI Action
description: PowerBI deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  workspace_name_dashboard:
    description: 'Workspace Powerbi Name dashboard'
    required: true
    default: ''
  workspace_name_scenario:
    description: 'Workspace Powerbi Name scenario'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: PowerBI deployment
      env:
        powerbi_dashboard_view: ${{ github.action_path }}/../../../powerbi/dashboard/${{ env.PLATFORM_ID }}
        powerbi_scenario_view: ${{ github.action_path }}/../../../powerbi/scenario/${{ env.PLATFORM_ID }}
      run: |
        cd ${{ inputs.folder }}
        babylon powerbi workspace deploy "${{ inputs.workspace_name_dashboard }}" -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --type dashboard_view --folder $powerbi_dashboard_view/ --override
        babylon powerbi workspace deploy "${{ inputs.workspace_name_scenario }}" -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --type scenario_view --folder $powerbi_scenario_view/ --override  
      shell: bash

