name: WebApp Deploy Action
description: WebApp Deploy with powerbi and azure function option
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  context_id:
    description: 'Context Name'
    required: true
    default: 'asset'
  platform_id:
    description: 'Platform Name'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: webapp deployment with powerbi and azure function
      run: |
        cd ${{ inputs.folder }}
        babylon webapp deploy -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --with-azf 
        babylon powerbi workspace user add -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} %app%principal_id App Admin
        babylon azure iam set -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --resource-type Microsoft.EventHub/Namespaces --role-id %azure%eventhub_built_data_sender --principal-id %app%principal_id 
      shell: bash