name: WebApp Deploy Action
description: WebApp Deploy with powerbi and azure function option
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  powerbi:
    description: 'bool'
    required: true
    default: 'false'
  azf:
    description: 'bool'
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: webapp deployment without powerbi and azure function
      if: ${{ inputs.powerbi == 'false' && inputs.azf == 'false'  }}
      run: |
        cd ${{ inputs.folder }}
        babylon webapp deploy
      shell: bash
    - name: webapp deployment with powerbi
      if: ${{ inputs.powerbi == 'true' && inputs.azf == 'false' }}
      run: |
        cd ${{ inputs.folder }}
        babylon webapp deploy --enable-powerbi
      shell: bash
    - name: webapp deployment with azure function
      if: ${{ inputs.powerbi == 'false' && inputs.azf == 'true' }}
      run: |
        cd ${{ inputs.folder }}
        babylon webapp deploy --enable-azfunc --azfunc-path ${{ github.action_path }}/../../arm/azf_deploy.json
      shell: bash
    - name: webapp deployment with powerbi and azure function
      if: ${{ inputs.powerbi == 'true' && inputs.azf == 'true'  }}
      run: |
        cd ${{ inputs.folder }}     
        babylon webapp deploy --enable-powerbi --enable-azfunc --azfunc-path ${{ github.action_path }}/../../arm/azf_deploy.json
      shell: bash
