name: Clone Action
description: Clone any version of sample Web App
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  repo_from:  
    description: 'Github Repository source'
    required: true
    default: ''
  repo_to:  
    description: 'Github Repository target'
    required: true
    default: ''
  repo_tag:  
    description: 'Sample Webapp version'
    required: true
    default: 'v5.0.0'
  repo_to_branch:  
    description: 'Github Repository target branch'
    required: true
    default: 'main'
  username:  
    description: 'Username'
    required: true
    default: ''
  email:  
    description: 'Email'
    required: true
    default: ''
  pat:
    description: 'Personal Access Token Github (repo/workflows)'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Clone any version of sample Web App
      run: |
        git config --global pull.rebase true
        git config --global init.defaultBranch main
        git config --global user.name ${{ inputs.username }}
        git config --global user.email ${{ inputs.email }}
        cd ${{ inputs.folder }}; mkdir webapp; cd webapp
        git init
        echo "# empty_webapp" >> README.md
        git add README.md
        git commit -m "first commit"
        git branch -M main
        git remote add origin https://Cosmo-Tech:${{inputs.pat}}@github.com/${{ inputs.repo_to }}.git
        git remote add upstream https://oauth2:${{inputs.pat}}@github.com/${{ inputs.repo_from }}.git
        git remote set-url upstream --push "NO"
        git fetch --all --tags --prune
        git checkout -B ${{ inputs.repo_to_branch }} ${{ inputs.repo_tag }}
        rm -r .github/
        git add .; git commit -m 'first commit'
        git push origin ${{ inputs.repo_to_branch }} -f
      shell: bash
