name: Setup environment variables Action
description: Setup environment variables
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  context_id:
    description: 'Context Name'
    required: true
    default: 'asset'
  platform_id:
    description: 'Platform Name'
    required: true
    default: 'dev'
  email:  
    description: 'Email'
    required: true
    default: ''
  user_principal_id:  
    description: 'user_principal_id (Azure Directory)'
    required: true
    default: ''
  workspace_key:  
    description: 'workspace_key'
    required: true
    default: ''
  team_id:  
    description: 'azure team_id'
    required: true
    default: ''
  simulator_image_docker:
    description: 'simulator_image_docker'
    required: true
    default: ''
  simulator_version:
    description: 'simulator_version'
    required: true
    default: ''
  uri_artifact_zip:
    description: 'uri_artifact_zip'
    required: true
    default: ''
  deployment_name:
    description: 'deployment_name'
    required: true
    default: ''
  location:
    description: 'location'
    required: true
    default: ''
  repo_to:
    description: 'repo_to : The repository in which we will perform the deployment'
    required: true
    default: ''
  repo_to_branch:
    description: 'repo_to_branch : The branch in which we will perform the deployment '
    required: true
    default: ''
  organization:
    description: 'Github Organisation Cosmo-Tech'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup environment variables
      run: |
        cd ${{ inputs.folder }}
        babylon config set azure email "${{ inputs.email }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set azure user_principal_id "${{ inputs.user_principal_id }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set api workspace_key "${{ inputs.workspace_key }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set powerbi dashboard_view -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
      # babylon config set powerbi scenario_view -c brewery -p perf 
        babylon config set azure team_id "${{ inputs.team_id }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set acr simulator_repository "${{ inputs.simulator_image_docker }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set acr simulator_version "${{ inputs.simulator_version }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set azure function_artifact_url "${{ inputs.uri_artifact_zip }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set webapp deployment_name "${{ inputs.deployment_name }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set webapp location "${{ inputs.location }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set github branch "${{ inputs.repo_to_branch }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set github organization "${{ inputs.organization }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon config set github repository "${{ inputs.repo_to }}" -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        # setup run_templates
        babylon config set api run_templates -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --item "common"
      shell: bash

