name: Pull Image from Azure Container Registry

description: Pulles image from Azure Container Registry

inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  simulator_image_docker:
    description: 'simulator_image_docker'
    required: true
    default: ''
  simulator_version:
    description: 'simulator_version'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Pull ACR simulator image
      run: |
        cd ${{ inputs.folder }}
        babylon azure acr pull -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --image ${{ inputs.simulator_image_docker }}:${{ inputs.simulator_version }}
        docker tag ${{ inputs.simulator_image_docker }}:${{ inputs.simulator_version }} mtor:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_${{ env.PLATFORM_ID }}Z
      shell: bash
