name: Storage Container Deploy Action
description: Create storage container by default
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  platforms:
    description: 'List of platforms'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: Create storage container by default
      run: |
        IFS=',' read -ra platforms_array <<< "${{ inputs.platforms }}"
        for platform in "${platforms_array[@]}"; do
            cleaned_platform=$(echo "$platform" | sed 's/ *//g')
            if [ "$cleaned_platform" == "${{ env.PLATFORM_ID }}" ]; then
                cd ${{ inputs.folder }}
                organization_id=$(babylon config get -c ${{ env.CONTEXT_ID }} -p $cleaned_platform api organization_id)
                babylon azure storage container create $organization_id -c ${{ env.CONTEXT_ID }} -p $cleaned_platform
            fi
        done  
      shell: bash
