name: Storage Container Deploy Action
description: Create storage container name given
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  name:
    description: 'Container name'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Create storage container by default
      if: ${{ inputs.name == '' }}
      run: |
        cd ${{ inputs.folder }}
        babylon azure storage container create -s
      shell: bash

    - name: Create storage container name given
      if: ${{ inputs.name != '' }}
      run: |
        cd ${{ inputs.folder }}
        babylon azure storage container create "${{ inputs.name }}"
      shell: bash
