name: ADX Action
description: ADX datavbase deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  team_id:
    description: 'azure team id'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Azure Data Explorer deployment
      env:
        ADX: ${{ github.action_path }}/../../../adx
      run: |
        cd ${{ inputs.folder }}
        babylon azure adx database create -s
        babylon azure adx script run-folder $ADX
        babylon azure adx permission set -t App -r Admin
        babylon azure adx permission set -t Group -r Admin ${{ inputs.team_id }}
      shell: bash
