name: ADX Action
description: ADX datavbase deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'  
  platforms:
    description: 'List of platforms'
    required: true
    default: 'dev'
  
runs:
  using: "composite"
  steps:
    - name: Azure Data Explorer deployment
      env:
        ADX: ${{ github.workspace }}/adx/${{ env.PLATFORM_ID }}
      run: |
        IFS=',' read -ra platforms_array <<< "${{ inputs.platforms }}"
        for platform in "${platforms_array[@]}"; do
            cleaned_platform=$(echo "$platform" | sed 's/ *//g')
            if [ "$cleaned_platform" == "${{ env.PLATFORM_ID }}" ]; then
                cd ${{ inputs.folder }}
                babylon azure adx database create -c ${{ env.CONTEXT_ID }} -p $cleaned_platform
                babylon azure adx permission set -c ${{ env.CONTEXT_ID }} -p $cleaned_platform --principal-type User --role Admin %azure%user_principal_id  
                babylon azure adx permission set -c ${{ env.CONTEXT_ID }} -p $cleaned_platform --principal-type Group --role Admin %azure%team_id
                babylon azure adx permission set -c ${{ env.CONTEXT_ID }} -p $cleaned_platform --principal-type App --role Admin %platform%principal_id
                babylon azure adx script run-folder $ADX -c ${{ env.CONTEXT_ID }} -p $cleaned_platform
            fi
        done
      shell: bash
