name: ADX Action
description: ADX datavbase deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  context_id:
    description: 'Context Name'
    required: true
    default: 'asset'
  platform_id:
    description: 'Platform Name'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: Azure Data Explorer deployment
      env:
        ADX: ${{ github.action_path }}/../../../adx
      run: |
        cd ${{ inputs.folder }}
        babylon azure adx database create -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
        babylon azure adx permission set -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --principal-type User --role Admin %azure%user_principal_id  
        babylon azure adx permission set -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --principal-type Group --role Admin %azure%team_id
        babylon azure adx permission set -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }} --principal-type App --role Admin %platform%principal_id
        babylon azure adx script run-folder $ADX -c ${{ inputs.context_id }} -p ${{ inputs.platform_id }}
      shell: bash
