name: Event hub namespace Action
description: Event hub namespace deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
runs:
  using: "composite"
  steps:
    - name: Event Hub Namespaces, connections and permissions deployment
      env:
        ARM: ${{ github.action_path }}/../../../.payload_templates/arm
      run: |
        cd ${{ inputs.folder }}
        babylon azure arm runtmp -f $ARM/eventhub_deploy.json
      shell: bash
    
    - name: add permissions
      run: |
        cd ${{ inputs.folder }}
        adx_cluster_pi=$(babylon config get-variable platform "adx_cluster_object_id")
        babylon azure permission set -rt Microsoft.EventHub/Namespaces -pi $adx_cluster_pi -ri a638d3c7-ab3a-418d-83e6-5f17a39d4fde
        babylon azure permission set -rt Microsoft.EventHub/Namespaces -ri 2b629674-e913-4c01-ae53-ef4638d8f975
      shell: bash

    - name: create connections
      run: |
        cd ${{ inputs.folder }}
        babylon azure adx connections create "ProbesMeasures" JSON -tn "ProbesMeasures" 
        babylon azure adx connections create "ScenarioMetaData" CSV -tn "ScenarioMetadata" 
        babylon azure adx connections create "ScenarioRun" JSON -tn "SimulationTotalFacts" 
        babylon azure adx connections create "ScenarioRunMetaData" CSV -tn "ScenarioRunMetadata"
      shell: bash