name: Event hub namespace Action
description: Event hub namespace deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  name:
    description: ''
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Event Hub Namespaces, connections and permissions deployment
      run: |
        cd ${{ inputs.folder }}
        babylon azure arm run -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --file %templates%/arm/eventhub_deploy.json ${{ inputs.name }}
      shell: bash
    
    - name: add permissions
      run: |
        cd ${{ inputs.folder }}
        babylon azure iam set -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --resource-type Microsoft.EventHub/Namespaces --role-id %azure%eventhub_built_data_receiver --principal-id %adx%cluster_principal_id
        babylon azure iam set -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --resource-type Microsoft.EventHub/Namespaces --role-id %azure%eventhub_built_data_sender --principal-id %platform%principal_id
        babylon azure iam set -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --resource-type Microsoft.EventHub/Namespaces --role-id %azure%eventhub_built_data_sender --principal-id %babylon%principal_id
        babylon azure iam set -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --principal-id %azure%team_id --principal-type Group --resource-type Microsoft.EventHub/Namespaces --role-id %azure%eventhub_built_contributor_id
      shell: bash

    - name: add consumer group 
      run: |
        cd ${{ inputs.folder }}
        babylon azure adx consumer add "adx" "ProbesMeasures" -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }}
        babylon azure adx consumer add "adx" "ScenarioMetaData" -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }}
        babylon azure adx consumer add "adx" "ScenarioRun" -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }}
        babylon azure adx consumer add "adx" "ScenarioRunMetaData" -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }}       
      shell: bash

    - name: create connections
      run: |
        cd ${{ inputs.folder }}
        babylon azure adx connections create -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} ProbesMeasures %adx%database_name --data-format JSON --table-name ProbesMeasures --compression GZip  --consumer-group adx --mapping ProbesMeasuresMapping
        babylon azure adx connections create -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} ScenarioMetaData %adx%database_name --data-format CSV --table-name ScenarioMetadata --consumer-group adx --mapping ScenarioMetadataMapping
        babylon azure adx connections create -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} ScenarioRun %adx%database_name --data-format JSON --table-name SimulationTotalFacts --consumer-group adx --mapping SimulationTotalFactsMapping
        babylon azure adx connections create -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} ScenarioRunMetaData %adx%database_name  --data-format CSV --table-name ScenarioRunMetadata --consumer-group adx --mapping ScenarioRunMetadataMapping
      shell: bash