name: Dataset Create Action
description: Dataset deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  type:
    description: 'Dataset Type'
    required: true
    default: ''
  name:
    description: 'Dataset Name'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Dataset deployment
      env:
        name: ${{ inputs.name }}
        type: ${{ inputs.type }}
      run: |
        cd ${{ inputs.folder }}
        babylon api datasets payload create -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --type $type
        babylon api datasets create "$name" -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --type $type 
      shell: bash
