name: Setup pat Action
description: Set variable pat in configuration
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  pat:
    description: 'Access token github repository'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: set variable pat on babylon configuration
      run: |
        cd ${{ inputs.folder }}
        babylon config set-variable secrets github.token ${{ inputs.pat }}
      shell: bash
