name: Push Image to Azure Container Registry

description: Pushes image to Azure Container Registry

inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  simulator_image_docker:
    description: 'simulator_image_docker'
    required: true
    default: ''
  simulator_version:
    description: 'simulator_version'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Push ACR simulator image
      run: |
        cd ${{ inputs.folder }}
        babylon azure acr push -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} --image mtor:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_${{ env.PLATFORM_ID }}Z
      shell: bash
