name: Push Image to Azure Container Registry

description: Pushes image to Azure Container Registry

inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  simulator_image_docker:
    description: 'simulator_image_docker'
    required: true
    default: ''
  simulator_version:
    description: 'simulator_version'
    required: true
    default: ''
  platforms:
    description: 'List of platforms to initialize'
    required: true

runs:
  using: "composite"
  steps:
    - name: Push ACR simulator image
      run: |
        cd ${{ inputs.folder }}
        IFS=',' read -ra platforms_array <<< "${{ inputs.platforms }}"
        for platform in "${platforms_array[@]}"; do
          if [ "$platform" != "${{ env.PLATFORM_ID }}" ]; then 
            docker tag ${{ inputs.simulator_image_docker }}:${{ inputs.simulator_version }} ${{ inputs.simulator_image_docker }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
            babylon azure acr push -c ${{ env.CONTEXT_ID }} -p $platform --image ${{ inputs.simulator_image_docker }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
          fi
        done
      shell: bash
