name: Upload handlers
description: Upload the 3 handler prerun, postrun, parameter handler
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  item:
    description: 'item'
    required: true
    default: ''
  platforms:
    description: 'List of platforms'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: Upload handlers
      env:
        HANDLERS: ${{ github.workspace }}/handlers/${{ env.PLATFORM_ID }}
      run: |
        IFS=',' read -ra platforms_array <<< "${{ inputs.platforms }}"
        for platform in "${platforms_array[@]}"; do
            cleaned_platform=$(echo "$platform" | sed 's/ *//g')
            if [ "$cleaned_platform" == "${{ env.PLATFORM_ID }}" ]; then
                cd ${{ inputs.folder }}
                babylon api solutions handler upload --run-template ${{ inputs.item }} -c ${{ env.CONTEXT_ID }} -p $cleaned_platform parameters_handler $HANDLERS/parameters_handler.zip
                babylon api solutions handler upload --run-template ${{ inputs.item }} -c ${{ env.CONTEXT_ID }} -p $cleaned_platform prerun $HANDLERS/prerun.zip
                babylon api solutions handler upload --run-template ${{ inputs.item }} -c ${{ env.CONTEXT_ID }} -p $cleaned_platform postrun $HANDLERS/postrun.zip
            fi
        done  
      shell: bash