name: Event Key Action
description: Authentication Eventhub configuration
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  resource_group:
    description: 'resource_group'
    required: true
    default: 'phoenixdev'
runs:
  using: "composite"
  steps:
    - name: Authentication Eventhub configuration
      run: |
        cd ${{ inputs.folder }}
        database_name=$(babylon config get -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }} adx database_name) 
        eventkey=$(az eventhubs namespace authorization-rule keys list -g ${{ inputs.resource_group }} --namespace-name $database_name --name RootManageSharedAccessKey --query primaryKey)
        babylon hvac set project eventhub $eventkey -c ${{ env.CONTEXT_ID }} -p ${{ env.PLATFORM_ID }}
      shell: bash