name: Connector Action
description: Connector deployment
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  type:
    description: ''
    required: true
    default: ''
  name:
    description: ''
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Connector deployment
      env:
        name: ${{ inputs.name }}
        API: ${{ github.action_path }}/.payload_templates/api
        type: ${{ inputs.type }} | tr [:upper:] [:lower:]
      run: |
        cd ${{ inputs.folder }}
        babylon api connector create $name -i "$API/connector.$type.yaml" -t $type -s
      shell: bash
